WICG/layout-instability

README.md
This PR makes a number of updates to the layout instability metric explainer:
- Put key terms in bold at their point of definition.
- Describe move distance and distance fraction.
- Describe exclusion of transform changes.
- Clarify rationale for 3px threshold.
- Add hadRecentInput and lastInputTime to LayoutShift.
- Describe recent input exclusion.
- Check hadRecentInput in sample code (matching demo).
- Explain buffered flag, don't suggest getEntriesByType.
=> Update explainer for move distance, input exclusion, etc.

index.bs
Update the spec to reflect the new `hadRecentInput` and `lastInputTime` attributes on the `LayoutShift` interface.
Also, rename the entry type from "layoutShift" to "layout-shift", and add the buffered flag to the usage example.
Also, update the wording about the transform exclusion, and make it normative instead of a note.
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/17.html" title="Last updated on Jul 16, 2019, 3:36 PM UTC (4bb6144)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/17/85acb05...skobes:4bb6144.html" title="Last updated on Jul 16, 2019, 3:36 PM UTC (4bb6144)">Diff</a>
=> Update spec for input exclusion attributes.

index.bs
For greater clarity, express logic principally through concept
definitions instead of algorithms.
Codify the CSS transform exclusion more precisely, and extend it to
scrolling.
Define visual representation for elements with reference to CSS
Display and Fragmentation specs for box and fragment concepts.
Define visual representation for text with reference to line boxes.
Specify that the first fragment determines the starting point.
General cleanup and simplification.
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/22.html" title="Last updated on Aug 13, 2019, 7:35 PM UTC (31c8721)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/22/4bb6144...skobes:31c8721.html" title="Last updated on Aug 13, 2019, 7:35 PM UTC …
=> Refactor the Layout Instability API spec.

index.bs
For issue https://github.com/WICG/layout-instability/issues/28
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/29.html" title="Last updated on Oct 18, 2019, 6:35 PM UTC (3fe5996)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/29/0fea94b...skobes:3fe5996.html" title="Last updated on Oct 18, 2019, 6:35 PM UTC (3fe5996)">Diff</a>
=> Expand introduction in spec.

index.bs
Fixes https://github.com/WICG/layout-instability/issues/30. Also fix a warning about not using 'must' in a non-normative section.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/31.html" title="Last updated on Feb 26, 2020, 7:06 PM UTC (f92d80d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/31/ba0f51e...f92d80d.html" title="Last updated on Feb 26, 2020, 7:06 PM UTC (f92d80d)">Diff</a>
=> Fix usage of takeRecords in example

sources.md
***
:boom: ###
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 17, 2020, 1:02 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2FWICG%2Flayout-instability%2Fpull%2F33%2Fcbf530f.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fskobes%2Flayout-instability%2Fpull%2F33.html)
_If you don't have enough information above to solve the error by yourself (or to understand to …
=> Start explainer for shifted element surfacing.

.travis.yml
Bikeshed is now requiring it so builds are failing.
=> Update Python to 3.7

index.bs
Previous review thread: https://github.com/WICG/layout-instability/pull/32.
This version now incorporates a procedural algorithm to report the layout shift sources, and sets the node attribute to null when the shifted node is detached or inside shadow DOM (reusing the "get an element" algorithm from the Element Timing spec, as discussed).
The sources attribute is now a sequence instead of a FrozenArray.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 27, 2020, 5:43 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to …
=> Add shifted element attribution (#11).

index.bs
Relevant issue: https://github.com/w3c/performance-timeline/issues/162
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 27, 2020, 5:58 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FWICG%2Flayout-instability%2F329288da9f04aa35a8a09766c02af4c636e69454%2Findex.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: 1.
Bikeshed has updated to Python 3, but you are trying to run it …
```
=> Set the realm of new objects

index.bs
Fixes #40 .
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/41.html" title="Last updated on Mar 27, 2020, 9:24 PM UTC (dad24b8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/41/3171ca5...skobes:dad24b8.html" title="Last updated on Mar 27, 2020, 9:24 PM UTC (dad24b8)">Diff</a>
=> Use FrozenArray instead of sequence.

index.bs
No comma between company and URL of the company.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/43.html" title="Last updated on May 12, 2020, 8:50 PM UTC (de77a88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/43/99c3887...de77a88.html" title="Last updated on May 12, 2020, 8:50 PM UTC (de77a88)">Diff</a>
=> Fix editor syntax

index.bs
(apologies for the pedantry)
The spec has a few instances of "...the greater of X or Y"
Strictly speaking, that should say "and", not "or", I think.
Mathematically speaking:
* "X **and** Y" represents a set of two values which we can perform a "give-me-the-greatest-value" operation on.
*...whereas "X **or** Y" represents a single (indeterminate) value, and it doesn't really make sense to perform a give-me-the-greatest-value operation on that single indeterminate value.
Also, consistency-wise (and as a sanity-check on my instinct here): CSS specs do seem to say "the greatest of X **and** Y" (rather than "or"), when they use this sort of phrasing.
e.g.:
> the greater of the number determined by the table-column elements **and** the number determined by the first row, …
=> s/or/and/ in "greater of X or Y" expressions

index.bs
Some paragraphs that introduce the idea of a cumulative score are moved
into this section as well.
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/58.html" title="Last updated on Jul 31, 2020, 8:54 PM UTC (3ebd643)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/58/5a5126f...skobes:3ebd643.html" title="Last updated on Jul 31, 2020, 8:54 PM UTC (3ebd643)">Diff</a>
=> Rename section 1.1 "Cumulative Layout Shift".

index.bs
Fixes https://github.com/WICG/layout-instability/issues/47
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/69.html" title="Last updated on Sep 2, 2020, 6:25 PM UTC (88b7e3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/69/3f1d40c...88b7e3c.html" title="Last updated on Sep 2, 2020, 6:25 PM UTC (88b7e3c)">Diff</a>
=> Add note to explain the choice of 5 members

index.bs
Fixes #50
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/70.html" title="Last updated on Sep 9, 2020, 8:52 PM UTC (80473f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/70/0ba1256...skobes:80473f0.html" title="Last updated on Sep 9, 2020, 8:52 PM UTC (80473f0)">Diff</a>
=> Include per-frame scores and timestamps in example.

index.bs
Fixes #62 
This is simpler than my previous proposal of viewport height + element height, and probably better in the case of pathologically large elements.
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/73.html" title="Last updated on Sep 10, 2020, 5:10 PM UTC (38b86a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/73/0ba1256...skobes:38b86a6.html" title="Last updated on Sep 10, 2020, 5:10 PM UTC (38b86a6)">Diff</a>
=> Clamp move vector to 2x viewport.

index.bs
Adopts the suggestion of http://crbug.com/1109053#c6 where wangxianzhu correctly notes:
it seems unnecessary to mention "local coordinate system" at all. We can just calculate the starting point from the viewport or scroll parent as if the transforms don't exist"
Fixes #59
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/72.html" title="Last updated on Sep 12, 2020, 1:31 AM UTC (fd00b57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/72/0ba1256...skobes:fd00b57.html" title="Last updated on Sep 12, 2020, 1:31 AM UTC (fd00b57)">Diff</a>
=> Fix specification of transform-change exclusion.

index.bs
This change had no effect, because the distance fraction had its own
(stricter) clamp.
This reverts commit 38b86a6bf86564062753bfb32b09f43e6111396b.
Fixes #62
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/74.html" title="Last updated on Sep 15, 2020, 2:53 PM UTC (eb51c25)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/74/33f53de...skobes:eb51c25.html" title="Last updated on Sep 15, 2020, 2:53 PM UTC (eb51c25)">Diff</a>
=> Revert "Clamp move vector to 2x viewport."

index.bs
For https://github.com/WICG/layout-instability/issues/76
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/77.html" title="Last updated on Sep 21, 2020, 8:47 PM UTC (6c47db0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/77/3047605...6c47db0.html" title="Last updated on Sep 21, 2020, 8:47 PM UTC (6c47db0)">Diff</a>
=> Trivial update

index.bs
Wrap security-privacy paragraph to 100, to regenerate the spec in latest bikeshed. Fixes https://github.com/WICG/layout-instability/issues/76
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/79.html" title="Last updated on Sep 29, 2020, 2:18 PM UTC (20e21c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/79/3c3132d...20e21c7.html" title="Last updated on Sep 29, 2020, 2:18 PM UTC (20e21c7)">Diff</a>
=> Regenerate spec

index.bs
Fixes https://github.com/WICG/layout-instability/issues/78
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/82.html" title="Last updated on Oct 6, 2020, 4:56 PM UTC (619f79c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/82/d939e7b...619f79c.html" title="Last updated on Oct 6, 2020, 4:56 PM UTC (619f79c)">Diff</a>
=> Pass global object to current high res time

index.bs
We should not consider a node unstable if its computed visibility or opacity are hidden/0 in the frame or previous frame.
Addresses https://github.com/WICG/layout-instability/issues/61
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/91.html" title="Last updated on Jan 27, 2021, 7:09 PM UTC (99ae49f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/91/86f1dcb...99ae49f.html" title="Last updated on Jan 27, 2021, 7:09 PM UTC (99ae49f)">Diff</a>
=> Clarify opacity and visibility in spec

index.bs
When determining whether the node can be considered unstable, we need to consider not just the node but also its ancestors, since computed value does not account for inheritance. Fixes https://github.com/WICG/layout-instability/issues/61
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/96.html" title="Last updated on Feb 24, 2021, 6:12 PM UTC (f9816d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/96/f831584...f9816d3.html" title="Last updated on Feb 24, 2021, 6:12 PM UTC (f9816d3)">Diff</a>
=> Fix computed value computation

index.bs
Fixes https://github.com/WICG/layout-instability/issues/95
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/97.html" title="Last updated on Mar 1, 2021, 6:46 PM UTC (297b6f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/97/c204348...297b6f6.html" title="Last updated on Mar 1, 2021, 6:46 PM UTC (297b6f6)">Diff</a>
=> State that change events are excluding

index.bs
Fixes #98
***
<a href="https://pr-preview.s3.amazonaws.com/skobes/layout-instability/pull/101.html" title="Last updated on Apr 6, 2021, 11:28 PM UTC (1260fbb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/101/0043ac9...skobes:1260fbb.html" title="Last updated on Apr 6, 2021, 11:28 PM UTC (1260fbb)">Diff</a>
=> Ignore inline clip crossers.

index.bs
As a non-native speaker, I had no idea what "fling" meant. It seems to be an Android specific term. 
Even in the Android community, it might not be that well understood: From [Advanced Android Application Development: Handling Advanced User Input](https://www.informit.com/articles/article.aspx?p=2262133&seqNum=3)
> onFling: Called after the user presses and then moves a finger in an accelerating motion before lifting it. This is commonly called a flick gesture and usually results in some motion continuing after the user lifts the finger.
***
<a href="https://pr-preview.s3.amazonaws.com/rik/layout-instability/pull/102.html" title="Last updated on Apr 15, 2021, 10:59 PM UTC (c9371fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/102/0b186d4...rik:c9371fd …
=> Replace fling by the commonly known flick

index.bs
Fixes https://github.com/WICG/layout-instability/issues/53
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/111.html" title="Last updated on Oct 18, 2021, 2:44 PM UTC (cc27d3f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/111/d6fcc96...cc27d3f.html" title="Last updated on Oct 18, 2021, 2:44 PM UTC (cc27d3f)">Diff</a>
=> Make number of pixels configurable by user agent

index.bs
Fixes https://github.com/WICG/layout-instability/issues/81
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/pull/112.html" title="Last updated on Dec 20, 2021, 11:19 PM UTC (1033966)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/layout-instability/112/af30502...1033966.html" title="Last updated on Dec 20, 2021, 11:19 PM UTC (1033966)">Diff</a>
=> Add clarification about layout observer
